### PR TITLE
Modified authentication style from Service principal to managed ID

### PR DESCRIPTION
**Pull request by kyoro1**
Replaced authentication method from service principal to managed ID. Can you check it, @Zachary-Syd ?

Also, it's related #2

### CODE REVIEW

**Comment by Ray0light** [comment]
Awesome

**Review by Ray0light — APPROVED** [review]

**Review by Zachary-Syd — CHANGES_REQUESTED** [review]
Great work! I have some comments as follows.
1. Should we update some instruction for the users in terms how to set up the environment variable "managed ID"? It shows "Managed ID: None" in "00. provisioning.ipynb".
2. There is a typo to be fixed in Line 318 of "src/common/azureml_configuration.py".

**Review by Ray0light — APPROVED** [review]

**Comment by kyoro1** [comment]
@Zachary-Syd , I changed some explanation with your suggesion. Can you check it on your end?

**Comment by Zachary-Syd** [comment]
Great work!

**Review by Zachary-Syd — APPROVED** [review]
Great work!

**Comment by kyoro1** [comment]
Can we merge the updates to the master?

**Pull request merged**
